repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        name: Minor auto-fixes
        exclude: ^(?:node_modules|dist|build|public)/|^src/locales/[^/]+\.json$

  - repo: local
    hooks:
      - id: translations
        name: Maintain translations
        language: system
        entry: bash -c 'npm run translations && git add -- src/locales translation_coverage'
        pass_filenames: false
        always_run: true

      - id: editorconfig-checker-docker
        name: Check .editorconfig rules
        language: docker_image
        entry: mstruebing/editorconfig-checker:latest
        args: ["ec", "-no-color"]
        types_or: [text]
        exclude: ^(node_modules|dist|build|public)/
