export type ConfigMap = {
	/*
	 * Vite-specific environment variables.
	 * These can't or shouldn't be set at runtime.
	 */
	VITE_HOST?: string;
	VITE_PORT?: string;
	VITE_GENERATE_SOURCEMAP?: string;
	VITE_APP_VERSION?: string;

	/*
	 * Runtime injected variables.
	 * These should be injected into index.html as meta tags.
	 *
	 * If in a multi-tenancy setup, these *should* likely differ between tenants.
	 */
	META_STATIC_PUBLIC_URL: string;
	META_STATIC_NAME: string;
	META_I18N_WALLET_NAME_OVERRIDE: string;
	META_OPENID4VCI_REDIRECT_URI: string;

	/*
	 * Runtime injected variables.
	 * These should be injected into index.html as meta tags.
	 *
	 * If in a multi-tenancy setup, these *should not* likely differ between tenants.
	 */
	META_WS_URL: string;
	META_WALLET_BACKEND_URL: string;
	META_LOGIN_WITH_PASSWORD: string;
	META_DID_KEY_VERSION: string;
	META_DISPLAY_CONSOLE: string;
	META_WEBAUTHN_RPID: string;
	META_OPENID4VCI_PROOF_TYPE_PRECEDENCE: string;
	META_OPENID4VP_SAN_DNS_CHECK: string;
	META_OPENID4VP_SAN_DNS_CHECK_SSL_CERTS: string;
	META_VALIDATE_CREDENTIALS_WITH_TRUST_ANCHORS: string;
	META_MULTI_LANGUAGE_DISPLAY: string;
	META_FOLD_EVENT_HISTORY_AFTER_SECONDS: string;
	META_DISPLAY_ISSUANCE_WARNINGS: string;
	META_OPENID4VCI_MAX_ACCEPTED_BATCH_SIZE: string;
	META_OPENID4VCI_TRANSACTION_ID_POLLING_INTERVAL_IN_SECONDS: string;
	META_OPENID4VCI_TRANSACTION_ID_LIFETIME_IN_SECONDS: string;
	META_OHTTP_KEY_CONFIG: string;
	META_OHTTP_RELAY: string;
	META_VCT_REGISTRY_URL: string;

	/*
	 * Data for well-known files.
	 * Are not injected as meta tags.
	 */
	WELLKNOWN_APPLE_APPIDS: string;
	WELLKNOWN_ANDROID_PACKAGE_NAMES_AND_FINGERPRINTS: string;

}

export function getConfigFromEnv(env: Record<string, string>): ConfigMap {
	return {
		META_STATIC_PUBLIC_URL: env.VITE_STATIC_PUBLIC_URL,
		META_STATIC_NAME: env.VITE_STATIC_NAME,
		META_I18N_WALLET_NAME_OVERRIDE: env.VITE_I18N_WALLET_NAME_OVERRIDE,
		META_OPENID4VCI_REDIRECT_URI: env.VITE_OPENID4VCI_REDIRECT_URI,

		META_WS_URL: env.VITE_WS_URL,
		META_WALLET_BACKEND_URL: env.VITE_WALLET_BACKEND_URL,
		META_LOGIN_WITH_PASSWORD: env.VITE_LOGIN_WITH_PASSWORD,
		META_DID_KEY_VERSION: env.VITE_DID_KEY_VERSION,
		META_DISPLAY_CONSOLE: env.VITE_DISPLAY_CONSOLE,
		META_WEBAUTHN_RPID: env.VITE_WEBAUTHN_RPID,
		META_OPENID4VCI_PROOF_TYPE_PRECEDENCE: env.VITE_OPENID4VCI_PROOF_TYPE_PRECEDENCE,
		META_OPENID4VP_SAN_DNS_CHECK	: env.VITE_OPENID4VP_SAN_DNS_CHECK,
		META_OPENID4VP_SAN_DNS_CHECK_SSL_CERTS: env.VITE_OPENID4VP_SAN_DNS_CHECK_SSL_CERTS,
		META_VALIDATE_CREDENTIALS_WITH_TRUST_ANCHORS: env.VITE_VALIDATE_CREDENTIALS_WITH_TRUST_ANCHORS,
		META_MULTI_LANGUAGE_DISPLAY: env.VITE_MULTI_LANGUAGE_DISPLAY,
		META_FOLD_EVENT_HISTORY_AFTER_SECONDS: env.VITE_FOLD_EVENT_HISTORY_AFTER_SECONDS,
		META_DISPLAY_ISSUANCE_WARNINGS: env.VITE_DISPLAY_ISSUANCE_WARNINGS,
		META_OPENID4VCI_MAX_ACCEPTED_BATCH_SIZE: env.VITE_OPENID4VCI_MAX_ACCEPTED_BATCH_SIZE,
		META_OPENID4VCI_TRANSACTION_ID_POLLING_INTERVAL_IN_SECONDS: env.VITE_OPENID4VCI_TRANSACTION_ID_POLLING_INTERVAL_IN_SECONDS,
		META_OPENID4VCI_TRANSACTION_ID_LIFETIME_IN_SECONDS: env.VITE_OPENID4VCI_TRANSACTION_ID_LIFETIME_IN_SECONDS,
		META_OHTTP_KEY_CONFIG: env.VITE_OHTTP_KEY_CONFIG,
		META_OHTTP_RELAY: env.VITE_OHTTP_RELAY,
		META_VCT_REGISTRY_URL: env.VITE_VCT_REGISTRY_URL,

		WELLKNOWN_APPLE_APPIDS: env.VITE_WELLKNOWN_APPLE_APPIDS,
		WELLKNOWN_ANDROID_PACKAGE_NAMES_AND_FINGERPRINTS: env.VITE_WELLKNOWN_ANDROID_PACKAGE_NAMES_AND_FINGERPRINTS,
	}
}
