name: Build Docker image
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build-front:
    permissions:
      contents: read
      packages: read

    uses: wwwallet/wallet-ecosystem/.github/workflows/docker-build-push.yml@a15f0fc1208fc00546ea73b4f21651f1c8bd8b27
    secrets: inherit
    with:
      image-tag: ghcr.io/wwwallet/wallet-frontend:latest
      docker-push: false
      dockerfile-target: test
      checkout-submodules: recursive
